routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//use Illuminate\Routing\Route;


//use Symfony\Component\Routing\Annotation\Route;

//use Symfony\Component\Routing\Route;


//Route::get('/', function () {
  //  return view('index');
//});
//Route::get('/',function(){
//  return view('titulo');
//});

Route::get('/', 'CarroController@destaque')
    ->name('carros.destaque');

Route::resource('carros', 'CarroController');

Route::resource('marcas', 'MarcaController');

Route::resource('propostas', 'PropostaController');

Route::resource('paineis','PainelController');

Route::get('carrosfoto/{id}', 'CarroController@foto')
    ->name('carros.foto');

Route::post('carrosfotostore', 'CarroController@storeFoto')
    ->name('carros.store.foto');


Route::get('carrospesq', 'CarroController@pesq')
    ->name('carros.pesq');

Route::get('carrosgraf', 'CarroController@graf')
    ->name('carros.graf');

Route::get('propostasgraf','PropostaController@graf')
    ->name('propostas.graf');

Route::post('carrosfiltros', 'CarroController@filtros')
    ->name('carros.filtros');

Route::get('propostas_list','PropostaController@index');
//---------------------------------------------

Route::post('carrosfiltros3', 'CarroController@filtros3')
    ->name('carros.filtros3');

Route::get('/home', 'CarroController@destaque')->name('carros.home');

Route::get('carrosstoredestaque/{id}', 'CarroController@storedestaque')
    ->name('carros.store.destaque');



Route::get('catalogo','CarroController@mostrar');

Route::get('user_pesquisa','CarroController@pesquisar');









//-------------------------------------------------------------------
Auth::routes();

Route::get('/arearestrita', 'HomeController@index');
/*
Route::get('register', function() {
    return "<h1> Acesso Restrito </h1>";
});*/

resources/views/carros_form.blade.php
@extends('principal')

@section('conteudo')

<script src="{{url('/js/jquery.mask.min.js')}}"></script>

<div class='col-sm-11'>
@if ($acao == 1)
    <h2> Inclusão de Carros </h2>
@else
    <h2> Alteração de Carros </h2>
@endif
</div>
<div class='col-sm-1'>
    <a href="{{route('carros.index')}}" class="btn btn-primary" 
       role="button">Voltar</a>
</div>

<div class='col-sm-12'>

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif        
    
@if ($acao == 1)
    <form method="post" action="{{route('carros.store')}}">
@else
    <form method="post" action="{{route('carros.update', $reg->id)}}">
    {!! method_field('put') !!}
@endif
        {{ csrf_field() }}

        <div class="form-group">
            <label for="modelo">Modelo do Veículo:</label>
            <input type="text" class="form-control" id="modelo"
                   name="modelo" 
                   value="{{$reg->modelo or old('modelo')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="marca_id">Marca:</label>
            <select class="form-control" id="marca_id" name="marca_id">
            @foreach($marcas as $m)    
            <option value="{{$m->id}}"
@if ((isset($reg) and $reg->marca_id == $m->id) or 
     old('marca_id') == $m->id) selected @endif>
                       {{$m->nome}}</option>
            @endforeach    
            </select>
        </div>
                
        <div class="form-group">
            <label for="cor">Cor:</label>
            <input type="text" class="form-control" id="cor"
                   name="cor" 
                   value="{{$reg->cor or old('cor')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="ano">Ano:</label>
            <input type="text" class="form-control" id="ano"
                   name="ano" 
                   value="{{$reg->ano or old('ano')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="preco">Preço R$:</label>
            <input type="text" class="form-control" id="preco"
                   name="preco" 
                   value="{{$reg->preco or old('preco')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="combustivel">Combustível:</label>
            <select class="form-control" id="combustivel" name="combustivel">
                <option value="A"
@if ((isset($reg) and $reg->combustivel == "Álcool") or 
     old('combustivel') == "A") selected @endif                        
                        >Álcool</option>
                <option value="G"
@if ((isset($reg) and $reg->combustivel == "Gasolina") or old('combustivel') == "G") selected @endif                                                
                        >Gasolina</option>
                <option value="D"
@if ((isset($reg) and $reg->combustivel == "Diesel") or old('combustivel') == "D") selected @endif                        
                        >Diesel</option>
                <option value="F"
@if ((isset($reg) and $reg->combustivel == "Flex") or old('combustivel') == "F") selected @endif                                                
                        >Flex</option>
            </select>
        </div>
        <div class="form-group">
            <label for="destaque">Destaque 0 ou 1:</label>
            <input type="text" class="form-control" id="destaque"
                   name="destaque"
                   value="{{$reg->destaque or old('estaque')}}"
                   required>
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>        
        <button type="reset" class="btn btn-warning">Limpar</button>        

    </form>
    </form>
</div>    

<script>
$(document).ready(function () {
    $('#preco').mask("#.###.##0,00", {reverse: true});
});
</script>    

@endsection

resources/views/carros_foto.blade.php
@extends('principal')

@section('conteudo')

<script src="{{url('/js/jquery.mask.min.js')}}"></script>

<div class='col-sm-11'>
    <h2> Cadastro de Fotos dos Carros </h2>
</div>
<div class='col-sm-1'>
    <a href="{{route('carros.index')}}" class="btn btn-primary" 
       role="button">Voltar</a>
</div>

<form method="post" action="{{route('carros.store.foto')}}"
      enctype="multipart/form-data">
    {{ csrf_field() }}
    
    <input type="hidden" name="id" value="{{$reg->id}}">

    <div class='col-sm-9'>
        <div class="form-group">
            <label for="modelo">Modelo do Veículo:</label>
            <input type="text" class="form-control" id="modelo"
                   name="modelo" 
                   value="{{$reg->modelo or old('modelo')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="marca_id">Marca:</label>
            <select class="form-control" id="marca_id" name="marca_id">
                @foreach($marcas as $m)    
                <option value="{{$m->id}}"
                        @if ((isset($reg) and $reg->marca_id == $m->id) or 
                        old('marca_id') == $m->id) selected @endif>
                        {{$m->nome}}</option>
                @endforeach    
            </select>
        </div>

        <div class="form-group">
            <label for="cor">Cor:</label>
            <input type="text" class="form-control" id="cor"
                   name="cor" 
                   value="{{$reg->cor or old('cor')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="ano">Ano:</label>
            <input type="text" class="form-control" id="ano"
                   name="ano" 
                   value="{{$reg->ano or old('ano')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="preco">Preço R$:</label>
            <input type="text" class="form-control" id="preco"
                   name="preco" 
                   value="{{$reg->preco or old('preco')}}"
                   required>
        </div>

        <div class="form-group">
            <label for="combustivel">Combustível:</label>
            <select class="form-control" id="combustivel" name="combustivel">
                <option value="A"
                        @if ((isset($reg) and $reg->combustivel == "Álcool") or 
                        old('combustivel') == "A") selected @endif                        
                        >Álcool</option>
                <option value="G"
                        @if ((isset($reg) and $reg->combustivel == "Gasolina") or old('combustivel') == "G") selected @endif                                                
                        >Gasolina</option>
                <option value="D"
                        @if ((isset($reg) and $reg->combustivel == "Diesel") or old('combustivel') == "D") selected @endif                        
                        >Diesel</option>
                <option value="F"
                        @if ((isset($reg) and $reg->combustivel == "Flex") or old('combustivel') == "F") selected @endif                                                
                        >Flex</option>
            </select>
        </div>

        <button type="submit" class="btn btn-primary">Enviar</button>        
        <button type="reset" class="btn btn-warning">Limpar</button>        
    </div>    
    
    <div class="col-sm-3" style="text-align: center">
@php        
    if(file_exists(public_path('fotos/'.$reg->id.'.jpg'))){
       $foto = '../fotos/'.$reg->id.'.jpg';
    } else {
       $foto = '../fotos/sem_foto.jpg';    
    }     
@endphp 
{!!"<img src=$foto id='imagem' width='200' height='150' alt='Foto'>"!!}
        <div class="form-group">
            <label for="foto"> Foto: </label>
            <input type="file" id="foto" name="foto" 
                   onchange="previewFile()"
                   class="form-control">
        </div>
    </div>
    
</form>    

<script>
function previewFile() {
    var preview = document.getElementById('imagem');
    var file    = document.getElementById('foto').files[0];
    var reader  = new FileReader();
    
    reader.onloadend = function() {
        preview.src = reader.result;
    };
    
    if (file) {
        reader.readAsDataURL(file);
    } else {
        preview.src = "";
    }    
}

$(document).ready(function () {
    $('#preco').mask("#.###.##0,00", {reverse: true});
});
</script>    

@endsection

resources/views/carros_list.blade.php
@extends('principal')

@section('conteudo')

<div class='col-sm-11'>
    <h2> Cadastro de Carros </h2>
</div>
<div class='col-sm-1'>
    <a href="{{route('carros.create')}}" class="btn btn-primary" 
       role="button">Novo</a>
</div>

<div class='col-sm-12'>

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif    
    
<table class="table table-hover">
    <thead>
      <tr>
        <th>Código</th>
        <th>Modelo do Veículo</th>
        <th>Marca</th>
        <th>Cor</th>
        <th>Ano</th>
        <th>Preço R$</th>
        <th>Combustível</th>
        <th>Data Cad.</th>
        <th>Ações</th>
        <th>Destaque</th>
      </tr>
    </thead>
    <tbody>
@foreach($carros as $carro)
<tr>
    <td style="text-align: center">{{$carro->id}}</td>
    <td>{{$carro->modelo}}</td>
    <td>{{$carro->marca->nome}}</td>
    <td>{{$carro->cor}}</td>
    <td>{{$carro->ano}}</td>
    <td style="text-align: right">{{number_format($carro->preco, '2', ',', '.')}} &nbsp;&nbsp;&nbsp;</td>
    <td>{{$carro->combustivel}}</td>
    <td>{{date_format($carro->created_at, 'd/m/Y')}}</td>
    <td>
       <a href="{{route('carros.edit', $carro->id)}}" 
          class="btn btn-warning" 
          role="button">Alterar</a> &nbsp;&nbsp;
       <form style="display: inline-block"
             method="post"
             action="{{route('carros.destroy', $carro->id)}}"
             onsubmit="return confirm('Confirma Exclusão?')">
             {{method_field('delete')}}
             {{csrf_field()}}
             <button type="submit"
                     class="btn btn-danger"> Excluir </button>
       </form> &nbsp;&nbsp;
       <a href="{{route('carros.foto', $carro->id)}}" 
          class="btn btn-info" 
          role="button">Foto</a>        
    </td>

    <td>
        <form method="GET" action="{{route('carros.store.destaque', $carro->id)}}">
            <input class="btn btn-primary" type="submit" value="Destaque">
        </form>
    </td>
</tr>
@endforeach        
    </tbody>
  </table>    
{{ $carros->links() }}
</div>

@endsection

resources/views/carros_pesq.blade.php
@extends('principal')
@section('conteudo')

    <div class="col-sm-11">
        <h2>Pesquisa de carros</h2>

    </div>

    <div class="col-sm-1">
        <a href="{{route('carros.pesq')}}" class="btn btn-primary" role="button">Ver todos</a>

    </div>


    <form method="post" action="{{route('carros.filtros')}}">
        {{csrf_field()}}

        <div class="col-sm-6">
            <div class="form-group">
                <label for="modelo">Modelo do veiculo:</label>
                <input type="text" class="form-control" id="modelo" name="modelo">
            </div>
        </div>



        <div class="col-sm-5">
            <div class="form-group">
                <label for="prcomax">Preço Máximo:</label>
                <input type="text" class="form-control" id="precomax" name="precomax">
            </div>

        </div>

        <div class="col-sm-1">
            <label> &nbsp</label>
            <div class="form-group">
                <button typeof="submit" class="btn btn-warning">pesquisar</button>

            </div>
        </div>
    </form>

    <div class='col-sm-12'>

        @if (count($carros)==0)
            <div class="alert alert-danger">
                Não há carros com os filtros informados...
            </div>
        @endif

        <table class="table table-hover">
            <thead>
            <tr>
                <th>Código</th>
                <th>Modelo do Veículo</th>
                <th>Marca</th>
                <th>Cor</th>
                <th>Ano</th>
                <th>Preço R$</th>
                <th>Combustível</th>
                <th>Data Cad.</th>
                <th>Ações</th>
            </tr>
            </thead>
            <tbody>
            @foreach($carros as $carro)
                <tr>
                    <td style="text-align: center">{{$carro->id}}</td>
                    <td>{{$carro->modelo}}</td>
                    <td>{{$carro->marca->nome}}</td>
                    <td>{{$carro->cor}}</td>
                    <td>{{$carro->ano}}</td>
                    <td style="text-align: right">{{number_format($carro->preco, '2', ',', '.')}} &nbsp;&nbsp;&nbsp;</td>
                    <td>{{$carro->combustivel}}</td>
                    <td>{{date_format($carro->created_at, 'd/m/Y')}}</td>
                    <td>
                        <a href="{{route('carros.edit', $carro->id)}}"
                           class="btn btn-warning"
                           role="button">Alterar</a> &nbsp;&nbsp;
                        <form style="display: inline-block"
                              method="post"
                              action="{{route('carros.destroy', $carro->id)}}"
                              onsubmit="return confirm('Confirma Exclusão?')">
                            {{method_field('delete')}}
                            {{csrf_field()}}
                            <button type="submit"
                                    class="btn btn-danger"> Excluir </button>
                        </form> &nbsp;&nbsp;
                        <a href="{{route('carros.foto', $carro->id)}}"
                           class="btn btn-info"
                           role="button">Foto</a>
                    </td>
                </tr>

            @endforeach
            </tbody>
        </table>
        {{$carros->links()}}
    </div>





@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/marcas_form.blade.php
@extends('principal')
@section('conteudo')

    <script src="{{url('/js/jquery.mask.min.js')}}"></script>

    <div class="col-sm-11">

        @if($acao == 1)

            <h2>Inclusão de Marcas</h2>

        @else

            <h2>Alteração de Marcas</h2>
        @endif

    </div>

    <div class="col-sm-1">
        <a href="{{route('marcas.index')}}" class="btn btn-primary" role="button">Voltar</a>
    </div>

    <div class="col-sm-12">

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif




        @if($acao == 1)
            <form method="post" action="{{route('marcas.store')}}">
                @else
                    <form method="post" action="{{route('marcas.update',$reg->id)}}">
                        {!! method_field('put') !!}
                        @endif


                        {{csrf_field()}}



                        <div class="form-group">
                            <label for="nome">Marca:</label>
                            <input type="text" class="form-control" id="nome" name="nome"  value="{{$reg->nome or old('nome')}}" required>
                        </div>


                        <div class="form-group">
                            <label for="pais">Pais:</label>
                            <input type="text" class="form-control" id="pais" name="pais" value="{{$reg->pais or old('pais')}}" required>
                        </div>

                        <button type="submit" class="btn btn-primary">Enviar</button>
                        <button type="reset" class="btn btn-warning">Limpar</button>

                    </form>
            </form>

    </div>


@endsection

resources/views/ofertas.blade.php
<html>
<head>
    <title>Revenda Herbie</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/css.css">
    <link rel="stylesheet" href="/css/clientPage.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="{{url('/js/jquery.mask.min.js')}}"></script>
    <script>
        $(document).ready(function(){
            $('#precomax').mask("#.###.##0,00", {reverse: true});
        });
    </script>
</head>
<body>
<header class="col-sm-12">
    <div class="col-sm-5">
        <a><h1 id="logo">REVENDA HERBIE</h1></a>
    </div>
    <div class="col-sm-7">
        <hr>
        <ul>
            <li><a href="{{'/'}}">Home</a>    |</li>
            <li><a href="{{('catalogo')}}">Catalogo </a>&nbsp;&nbsp; |</li>
            <li><a>Marcas </a>&nbsp;&nbsp; |</li>
            <li><a href="{{('user_pesquisa')}}">Pesquisas</a></li>
        </ul>
        <hr>
    </div>
</header>
<section class="col-sm-12">
    <hr><br>
    <div class="col-sm-1"></div>



    <div class="col-sm-2">
        <img src="public/fotos/heb.jpg" width="300" height="200">
    </div>
    <div class="col-sm-6"><h1 style="text-align: right;  font-family: 'Fredericka the Great', cursive;">Os melhores preços da cidade</h1></div>
    <div class="col-sm-6"><h1 style="text-align: right; font-family:  'Fredericka the Great', cursive;"   >Confie no fusca!!</h1></div>
</section>
</body>
    <div class="container">

        @if ($acao == 2)
            <section class="col-sm-6">
                @else
                    <section class="col-sm-12">
                        @endif
                  <hr>



<div class="col-sm-6">
    <br>
    @php
        if(file_exists(public_path('fotos/'.$reg->id.'.jpg'))){
            $foto = '/fotos/'.$reg->id.'.jpg';
        } else {
            $foto = '/fotos/sem_foto.jpg';
        }
    @endphp
    {!!"<img src=$foto id='imagem' width='400' height='300' alt='foto'>"!!}
</div>



<div class="col-sm-14">
    <h2 style="text-align: center; font-family: 'Fredericka the Great', cursive;">Detalhes</h2>

    <hr>
    <h3>Marca: {{$reg->marca->nome}}</h3>
    <hr>
    <h3>Modelo: {{$reg->modelo}}</h3>
    <hr>
    <h3>ano: {{$reg->ano}}</h3>
    <hr>
    <h3>Combustivel: {{$reg->combustivel}}</h3>
    <hr>
    <h3 style="text-align: center">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Preço R$: {{$reg->preco}}</h3>

    @if ($acao == 1)
</div>

        <div class="col-sm-12">

            <form method="post" action="{{route('propostas.store')}}">
                {{csrf_field()}}
                <input type="hidden" name="carro_id" id="carro_id"
                       value="{{$reg->id}}">
                <p>Nome: <input type="text" name="nome"
                                size="25" maxlength="25">

                <p> Telefone: <input type="text" name="telefone"
                                     size="25" maxlength="25">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    E-mail: <input type="email" name="email"
                                   size="25" maxlength="40">
                </p>
                <p>Valor: <input type="text" maxlength="6" name="preco"
                                 id="precomax"  value="{{$reg->preco or old('preco')}}">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="submit"
                           value="Enviar">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="reset"
                           value="Limpar"></p>
            </form>

        </div>



    @endif
    <hr>


    <hr>
    </section>
    @if ($acao == 2)
        <div class="col-sm-6">
            <hr>
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>código</th>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>Email</th>
                    <th>Valor</th>
                    <th>Data Cad</th>
                </tr>
                </thead>
                <tbody>
                @foreach($proposta as $prop)
                    <tr>
                        <td>{{$prop->id}}</td>
                        <td>{{$prop->nome}}</td>
                        <td>{{$prop->telefone}}</td>
                        <td>{{$prop->email}}</td>
                        <td>{{number_format($prop->preco, '2', ',', '.')}}</td>
                        <td>{{date_format ($prop->created_at, 'd/m/Y')}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        </section>
    @endif
</div>



<footer class="col-sm-12">

    <nav class="navbar navbar-default">
        <div class="container-fluid">

            <ul class="nav navbar-nav">
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a></li>




                <li><a href="#">Contatenos           </a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;|</a></li>
                <li><a href="#">Venha trabalhar conosco</a></li>
                <li><a href="#">&nbsp;&nbsp;&nbsp;&nbsp;|</a></li>
                <li><a href="#">Termos de uso</a></li>

            </ul>
        </div>
    </nav>
</footer>
</body>
</html>

resources/views/principal.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Revenda Herbie</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Revenda Herbie</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="{{url('/arearestrita')}}">Home</a></li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Cadastro <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{route('carros.index')}}">Carros</a></li>
                    <li><a href="{{route('marcas.index')}}">Marcas</a></li>
                    <li><a href="#">...</a></li>
                </ul>
            </li>
            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Graficos <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{route('carros.graf')}}">Carros</a></li>
                    <li><a href="{{route('propostas.graf')}}">Propostas</a></li>
                    <li><a href="#">...</a></li>
                </ul>
            </li>

            <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Pesquisas <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{route('carros.pesq')}}">Carros</a></li>
                    <li><a href="#">propostas</a></li>
                    <li><a href="#">...</a></li>
                </ul>
            </li>


            <li><a href="{{url('propostas_list')}}">Relatorio de Propostas</a></li>
            <li><a href="#">Utilitário</a></li>
        </ul>


        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"><span class="glyphicon glyphicon-user"></span> {{Auth::user()->name }}</a></li>
            <li>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
           document.getElementById('logout-form').submit();">
                    <span class="glyphicon glyphicon-log-in"></span>
                    Sair
                </a>

                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>


            </li>
        </ul>

    </div>
</nav>

<div class="container">
    @yield('conteudo')
</div>

</body>
</html>

resources/views/teste.blade.php
@extends('user_home')
@section('dest')


@endsection